spring:
  application:
    name: aggregator

  config:
    import: configserver:http://localhost:8888

  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

logging:
  level:
    org.springframework.cloud.config: DEBUG
    ru.yandex.practicum: DEBUG