server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: validate  # Проверять соответствие сущностей
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: shopping_store_schema
  sql:
    init:
      mode: always  # Создать таблицы по скрипту
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/commerce_shopping_store
    username: postgres
    password: 12345

# Детальное логирование SQL
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.datasource.init: DEBUG